name: Android
on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  Mobile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {install: true}
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Restore Previous Cache
        id: cache-debug-build-android-restore
        uses: actions/cache/restore@main
        with:
          path: |
            /home/runner/haxelib/
            export/release/android/haxe/
            export/release/android/obj/
          key: cache-android-build-new

      - name: Setup Haxelib
        run: haxelib setup ~/haxelib

      - name: Install Libraries
        if: matrix.config.install
        run: |
          yes | haxelib git hxcpp https://github.com/mcagabe19-stuff/hxcpp --quiet
          yes | haxelib git lime https://github.com/mcagabe19-stuff/lime-8.1.3 bb7f84595af862dd448205c1f217f96b1b85d193 --quiet
          yes | haxelib set openfl 9.3.3 --quiet
          yes | haxelib set flixel 5.6.1 --quiet
          yes | haxelib set flixel-addons 3.2.2 --quiet
          yes | haxelib set flixel-tools 1.5.1 --quiet
          yes | haxelib set hscript-iris 1.1.3 --quiet
          yes | haxelib set tjson 1.4.0 --quiet
          yes | haxelib set hxvlc 2.0.1 --quiet
          yes | haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate 768740a56b26aa0c072720e0d1236b94afe68e3e --quiet
          yes | haxelib git linc_luajit https://github.com/mcagabe19-stuff/linc_luajit-rewriten --quiet
          yes | haxelib git funkin.vis https://github.com/FunkinCrew/funkVis 9cac20547dd41505928eeca9c762c7e6b348f6f3 --quiet --skip-dependencies
          yes | haxelib git grig.audio https://gitlab.com/haxe-grig/grig.audio.git cbf91e2180fd2e374924fe74844086aab7891666 --quiet
          yes | haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools df9dfd0cda74e5460ae3afcfff1081c50959ed4a --quiet --skip-dependencies

      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true

      - name: Compile
        run: haxelib run lime build android -D officialBuild

      - name: Clear Previous Cache
        uses: actions/github-script@main
        with:
          script: |
            try {
            	const caches = await github.rest.actions.getActionsCacheList({
            		owner: context.repo.owner,
            		repo: context.repo.repo,
            	})
            	if (typeof caches.data.actions_caches != null && caches.data.actions_caches.length > 0) {
            		for (const cache of caches.data.actions_caches) {
            			if (cache.key == "cache-android-build-new") {
            				console.log('Clearing ' + cache.key + '...')
            				await github.rest.actions.deleteActionsCacheById({
            					owner: context.repo.owner,
            					repo: context.repo.repo,
            					cache_id: cache.id,
            				})
            				console.log("Previous Cache Cleared!")
            			}
            		}
            	}
            } catch (error) {
            	console.log(error.message);
            }

      - name: Save Current Cache
        id: cache-release-build-android-save
        uses: actions/cache/save@main
        with:
          path: |
            /home/runner/haxelib/
            export/release/android/haxe/
            export/release/android/obj/
          key: cache-android-build-new

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: PsychEngineModified-release
          path: export/release/android/bin/app/build/outputs/apk/release
          if-no-files-found: error